### ISSUE TITLE
[Improvement] Autocorrect and aliasing

### ISSUE THREAD

**Issue by Pk13055** [AIcrowd/aicrowd-cli#16]
Excellent structuring and usage of click btw! Check [this](https://github.com/story-archive/cli/blob/master/story/helpers/didyoumean.py) helper out for git-like did you mean functionality for mispelled command help. Additionally, [this](https://github.com/story-archive/cli/blob/master/story/helpers/aliases.py) provides an ability to alias (like git commands) for frequently used commands.

**Comment by nikhilrayaprolu** [comment]
Sure @Pk13055, It improves the user experience for the CLI. We will add this into our Road Map and prioritise it for the next release!
